### ISSUE TITLE
File "paragram_sl999_small.txt"

### ISSUE THREAD

**Issue by shreyansh26** [vgupta123/P-SIF#1]
Hi,

The file `paragram_sl999_small.txt` is not available on John Weiting's [Github](https://github.com/jwieting/iclr2016). Could you suggest where I could get it.

Also if I were to run the STS task on a custom set of documents what should it's format be? I was hoping going through `https://github.com/jwieting/iclr2016` would help me understand the better.

Help would be appreciated.

Thanks

**Comment by vgupta123** [comment]
Was your doubt resolved?

**Comment by shreyansh26** [comment]
Yes, I resolved this one, but I was playing around with P-SIF yesterday and had some other problems. I'll raise a separate issue for that.
