### ISSUE TITLE
STS on custom datasets

### ISSUE THREAD

**Issue by shreyansh26** [vgupta123/P-SIF#2]
Hi,

I wanted to run P-SIF on some custom text-based datasets that I have. How should I do that? Because currently it only works on the SentEval datasets and that too which have been processed and available in the form as in the file `parameters_gmm.csv`.

So how do I run it on my own text-based datasets?

Thanks

**Comment by vgupta123** [comment]
Hi Shreyansh

Let's walkover zoom/hangout tomorrow. I can help you with running code on custom dataset. Email me on keviv9 [al] gmail [dot] com

Regards
Vivek Gupta

**Comment by vgupta123** [comment]
You just need to replace the tsv file in 20 newsgroup to your tsv file and run with proper parameters. I can help you out also for the same in the call tomorrow.
