### ISSUE TITLE
"ValueError: The number of atoms cannot be more than the number of feature"

### ISSUE THREAD

**Issue by gm-spacagna** [vgupta123/P-SIF#3]
Hi, I am trying to use the ApproximateKSVD class and fit with a matrix of shape 5000x2048.

```
aksvd = ApproximateKSVD(n_components=10)
aksvd.fit(X)
```

But unfortunately, I get the following error:
"ValueError: The number of atoms cannot be more than the number of feature"

Anything I might be doing wrong?

Thanks

**Comment by gm-spacagna** [comment]
I think the error is to set transform_n_nonzero_coefs higher than the number of components (default is 10% of the dimensionality, thus 204 in my case).
Is there some rule of thumb for selecting the best value for transform_n_nonzero_coefs?
Thanks

**Comment by vgupta123** [comment]
No thumb rule, you need to tune it with respect to your data and feature dimensions.
